### PR TITLE
Fix feed issues

### LINKED ISSUE #33: Fix feed issues
[Feed Validator Results: https://krymtkts.github.io/blog-fable/feed.xml](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fkrymtkts.github.io%2Fblog-fable%2Ffeed.xml)

- lastBuildDate must be an RFC-822 date-time [element must be an RFC-822 date-time](https://validator.w3.org/feed/docs/error/InvalidRFC2822Date.html)
- [Self reference doesn't match document location](https://validator.w3.org/feed/docs/warning/SelfDoesntMatchLocation.html)
- Order `item` in descending order by `pubDate`

### PR DESCRIPTION
**Pull request by krymtkts**
Resolve #33

### CODE REVIEW

File: src/Generator.fs [hunk 1]
```diff
@@ -268,27 +268,33 @@ let generateFeed (conf: FeedConf) =
...
+            let pubDate =
+                let d =
+                    match meta.frontMatter with
+                    | Some fm ->
+                        match fm.date with
+                        | Some d -> d
+                        | None -> meta.date
+                    | None -> meta.date
+
+                d |> String.toRFC322DateTime
```
Comment (krymtkts) [inline src/Generator.fs:280]: use pipe directly

**Review by krymtkts — COMMENTED** [review]
ok for now.

TODOs are to be fixed later.
