### PR TITLE
Fix the bug caused the latest archive post generates the link to the future post.

### LINKED ISSUE #130: The latest post has a link to the unpublished future post.
t/o

### PR DESCRIPTION
**Pull request by krymtkts**
fix #130

### CODE REVIEW

File: src/Generator.fs [hunk 1]
```diff
@@ -315,10 +315,10 @@ module Rendering =
         promise {
             let! files = getMarkdownFiles sourceDir
             let! metas = files |> List.map readSource |> Promise.all
+            let metas = metas |> Array.filter (fun m -> m.publish)
```
Comment (krymtkts) [inline src/Generator.fs:318]: use `_.` shorthand
